//go:build !ignore_autogenerated

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

func (in *MDMProviderSpec) DeepCopyInto(out *MDMProviderSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.APITokenSecretRef != nil {
		in, out := &in.APITokenSecretRef, &out.APITokenSecretRef
		*out = new(SecretKeyReference)
		(*in).DeepCopyInto(*out)
	}
}

func (in *MDMProviderSpec) DeepCopy() *MDMProviderSpec {
	if in == nil {
		return nil
	}
	out := new(MDMProviderSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenantSpec) DeepCopyInto(out *ThothTenantSpec) {
	*out = *in
	in.AuthSecretRef.DeepCopyInto(&out.AuthSecretRef)
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MDMProvider != nil {
		in, out := &in.MDMProvider, &out.MDMProvider
		*out = new(MDMProviderSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ThothTenantSpec) DeepCopy() *ThothTenantSpec {
	if in == nil {
		return nil
	}
	out := new(ThothTenantSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenantStatus) DeepCopyInto(out *ThothTenantStatus) {
	*out = *in
	if in.LastPolicySyncAt != nil {
		in, out := &in.LastPolicySyncAt, &out.LastPolicySyncAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *ThothTenantStatus) DeepCopy() *ThothTenantStatus {
	if in == nil {
		return nil
	}
	out := new(ThothTenantStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenant) DeepCopyInto(out *ThothTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ThothTenant) DeepCopy() *ThothTenant {
	if in == nil {
		return nil
	}
	out := new(ThothTenant)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ThothTenantList) DeepCopyInto(out *ThothTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThothTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ThothTenantList) DeepCopy() *ThothTenantList {
	if in == nil {
		return nil
	}
	out := new(ThothTenantList)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
