//go:build !ignore_autogenerated

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

func (in *MDMProviderSpec) DeepCopyInto(out *MDMProviderSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.APITokenSecretRef != nil {
		in, out := &in.APITokenSecretRef, &out.APITokenSecretRef
		*out = new(SecretKeyReference)
		(*in).DeepCopyInto(*out)
	}
}

func (in *MDMProviderSpec) DeepCopy() *MDMProviderSpec {
	if in == nil {
		return nil
	}
	out := new(MDMProviderSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *MDMSyncSpec) DeepCopyInto(out *MDMSyncSpec) {
	*out = *in
	if in.WaitForCompletion != nil {
		in, out := &in.WaitForCompletion, &out.WaitForCompletion
		*out = new(bool)
		**out = **in
	}
}

func (in *MDMSyncSpec) DeepCopy() *MDMSyncSpec {
	if in == nil {
		return nil
	}
	out := new(MDMSyncSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WebhookSettingsSpec) DeepCopyInto(out *WebhookSettingsSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyReference)
		(*in).DeepCopyInto(*out)
	}
}

func (in *WebhookSettingsSpec) DeepCopy() *WebhookSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PolicyBundleSpec) DeepCopyInto(out *PolicyBundleSpec) {
	*out = *in
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *PolicyBundleSpec) DeepCopy() *PolicyBundleSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyBundleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PackAssignmentSpec) DeepCopyInto(out *PackAssignmentSpec) {
	*out = *in
	if in.PackIDs != nil {
		in, out := &in.PackIDs, &out.PackIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentIDs != nil {
		in, out := &in.AgentIDs, &out.AgentIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FleetIDs != nil {
		in, out := &in.FleetIDs, &out.FleetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EndpointIDs != nil {
		in, out := &in.EndpointIDs, &out.EndpointIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OverridesByPack != nil {
		in, out := &in.OverridesByPack, &out.OverridesByPack
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MismatchBoost != nil {
		in, out := &in.MismatchBoost, &out.MismatchBoost
		*out = new(float64)
		**out = **in
	}
	if in.DelegationBoost != nil {
		in, out := &in.DelegationBoost, &out.DelegationBoost
		*out = new(float64)
		**out = **in
	}
	if in.TrustFloor != nil {
		in, out := &in.TrustFloor, &out.TrustFloor
		*out = new(float64)
		**out = **in
	}
	if in.CriticalThreshold != nil {
		in, out := &in.CriticalThreshold, &out.CriticalThreshold
		*out = new(float64)
		**out = **in
	}
}

func (in *PackAssignmentSpec) DeepCopy() *PackAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(PackAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GovernanceEvidenceBackfillSpec) DeepCopyInto(out *GovernanceEvidenceBackfillSpec) {
	*out = *in
	if in.IncludeBlockedEvents != nil {
		in, out := &in.IncludeBlockedEvents, &out.IncludeBlockedEvents
		*out = new(bool)
		**out = **in
	}
}

func (in *GovernanceEvidenceBackfillSpec) DeepCopy() *GovernanceEvidenceBackfillSpec {
	if in == nil {
		return nil
	}
	out := new(GovernanceEvidenceBackfillSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GovernanceDecisionFieldBackfillSpec) DeepCopyInto(out *GovernanceDecisionFieldBackfillSpec) {
	*out = *in
	if in.IncludeBlockedEvents != nil {
		in, out := &in.IncludeBlockedEvents, &out.IncludeBlockedEvents
		*out = new(bool)
		**out = **in
	}
}

func (in *GovernanceDecisionFieldBackfillSpec) DeepCopy() *GovernanceDecisionFieldBackfillSpec {
	if in == nil {
		return nil
	}
	out := new(GovernanceDecisionFieldBackfillSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DecisionMetadataExportSpec) DeepCopyInto(out *DecisionMetadataExportSpec) {
	*out = *in
	if in.AuthTokenSecretRef != nil {
		in, out := &in.AuthTokenSecretRef, &out.AuthTokenSecretRef
		*out = new(SecretKeyReference)
		(*in).DeepCopyInto(*out)
	}
}

func (in *DecisionMetadataExportSpec) DeepCopy() *DecisionMetadataExportSpec {
	if in == nil {
		return nil
	}
	out := new(DecisionMetadataExportSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AppliedPolicyBundleStatus) DeepCopyInto(out *AppliedPolicyBundleStatus) {
	*out = *in
	in.AppliedAt.DeepCopyInto(&out.AppliedAt)
}

func (in *AppliedPolicyBundleStatus) DeepCopy() *AppliedPolicyBundleStatus {
	if in == nil {
		return nil
	}
	out := new(AppliedPolicyBundleStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenantSpec) DeepCopyInto(out *ThothTenantSpec) {
	*out = *in
	in.AuthSecretRef.DeepCopyInto(&out.AuthSecretRef)
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.MDMProvider != nil {
		in, out := &in.MDMProvider, &out.MDMProvider
		*out = new(MDMProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MDMSync != nil {
		in, out := &in.MDMSync, &out.MDMSync
		*out = new(MDMSyncSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookSettings != nil {
		in, out := &in.WebhookSettings, &out.WebhookSettings
		*out = new(WebhookSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyBundles != nil {
		in, out := &in.PolicyBundles, &out.PolicyBundles
		*out = make([]PolicyBundleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PackAssignments != nil {
		in, out := &in.PackAssignments, &out.PackAssignments
		*out = make([]PackAssignmentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GovernanceEvidenceBackfill != nil {
		in, out := &in.GovernanceEvidenceBackfill, &out.GovernanceEvidenceBackfill
		*out = new(GovernanceEvidenceBackfillSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GovernanceDecisionFieldBackfill != nil {
		in, out := &in.GovernanceDecisionFieldBackfill, &out.GovernanceDecisionFieldBackfill
		*out = new(GovernanceDecisionFieldBackfillSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DecisionMetadataExport != nil {
		in, out := &in.DecisionMetadataExport, &out.DecisionMetadataExport
		*out = new(DecisionMetadataExportSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ThothTenantSpec) DeepCopy() *ThothTenantSpec {
	if in == nil {
		return nil
	}
	out := new(ThothTenantSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenantStatus) DeepCopyInto(out *ThothTenantStatus) {
	*out = *in
	if in.LastWebhookTestAt != nil {
		in, out := &in.LastWebhookTestAt, &out.LastWebhookTestAt
		*out = (*in).DeepCopy()
	}
	if in.LastMDMSyncAt != nil {
		in, out := &in.LastMDMSyncAt, &out.LastMDMSyncAt
		*out = (*in).DeepCopy()
	}
	if in.LastPolicySyncAt != nil {
		in, out := &in.LastPolicySyncAt, &out.LastPolicySyncAt
		*out = (*in).DeepCopy()
	}
	if in.LastPolicyBundleApplyAt != nil {
		in, out := &in.LastPolicyBundleApplyAt, &out.LastPolicyBundleApplyAt
		*out = (*in).DeepCopy()
	}
	if in.AppliedPolicyBundles != nil {
		in, out := &in.AppliedPolicyBundles, &out.AppliedPolicyBundles
		*out = make([]AppliedPolicyBundleStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastGovernanceEvidenceBackfillAt != nil {
		in, out := &in.LastGovernanceEvidenceBackfillAt, &out.LastGovernanceEvidenceBackfillAt
		*out = (*in).DeepCopy()
	}
	if in.LastGovernanceDecisionFieldBackfillAt != nil {
		in, out := &in.LastGovernanceDecisionFieldBackfillAt, &out.LastGovernanceDecisionFieldBackfillAt
		*out = (*in).DeepCopy()
	}
	if in.LastDecisionMetadataExportAt != nil {
		in, out := &in.LastDecisionMetadataExportAt, &out.LastDecisionMetadataExportAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *ThothTenantStatus) DeepCopy() *ThothTenantStatus {
	if in == nil {
		return nil
	}
	out := new(ThothTenantStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenant) DeepCopyInto(out *ThothTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ThothTenant) DeepCopy() *ThothTenant {
	if in == nil {
		return nil
	}
	out := new(ThothTenant)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ThothTenantList) DeepCopyInto(out *ThothTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThothTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ThothTenantList) DeepCopy() *ThothTenantList {
	if in == nil {
		return nil
	}
	out := new(ThothTenantList)
	in.DeepCopyInto(out)
	return out
}

func (in *ThothTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
