replicaCount: 1

image:
  repository: ghcr.io/atensecurity/thoth-operator
  tag: "0.1.0@sha256:0ae098b9eb77fd0a55a8876537850e18c1e0309eefd1f6a8cd531b2b99a9712e"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

watchNamespace: ""

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
